name: ml_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  entries_api:
    path: packages/entries_api
  entries_repository:
    path: packages/entries_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_services_binding: ^0.1.0
  intl: ^0.17.0
  local_storage_entries_api:
    path: packages/local_storage_entries_api

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mockingjay: ^0.2.0
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true