name: ml_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_packages/authentication_repository
  bloc: ^8.0.3
  entries_api:
    path: packages/entries_packages/entries_api
  entries_repository:
    path: packages/entries_packages/entries_repository
  equatable: ^2.0.3
  flow_builder: ^0.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_services_binding: ^0.1.0
  flutterfire_ui: ^0.3.6
  font_awesome_flutter: ^10.1.0
  form_inputs:
    path: packages/authentication_packages/form_inputs
  formz: ^0.4.0
  intl: ^0.17.0
  local_storage_entries_api:
    path: packages/entries_packages/local_storage_entries_api
  url_launcher: ^6.0.18

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mockingjay: ^0.2.0
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/