// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYY7O59CaT9UMHsyTvJ2N6A2yMWnrCYaQ',
    appId: '1:895745841722:web:9d44c7abe77a0019e23303',
    messagingSenderId: '895745841722',
    projectId: 'mlapp-mostlearned',
    authDomain: 'mlapp-mostlearned.firebaseapp.com',
    storageBucket: 'mlapp-mostlearned.appspot.com',
    measurementId: 'G-J8KV3RJ9VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOwffD9p05dTUz3B4MDmqkzeEc5oomuZ0',
    appId: '1:895745841722:android:e0c72e64dd9000a1e23303',
    messagingSenderId: '895745841722',
    projectId: 'mlapp-mostlearned',
    storageBucket: 'mlapp-mostlearned.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqmGoDtvoB_Ey2UtNWUASNKNl8XWqJAqE',
    appId: '1:895745841722:ios:cbbbb38f835c7e13e23303',
    messagingSenderId: '895745841722',
    projectId: 'mlapp-mostlearned',
    storageBucket: 'mlapp-mostlearned.appspot.com',
    iosClientId: '895745841722-ffemt7ec0teloe64e0g77gs1ohm9qkhq.apps.googleusercontent.com',
    iosBundleId: 'com.mostlearned.mlapp',
  );
}
